
package amani.wechat.platform.webserviceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonServicePortType", targetNamespace = "http://services.amani.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonServicePortType {


    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveIPADBillInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveIPADBillInfo")
    @ResponseWrapper(localName = "saveIPADBillInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveIPADBillInfoResponse")
    public boolean saveIPADBillInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        SpadMconsumeInfo in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        ArrayOfSpadDconsumeInfo in1);

    /**
     * 
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfGoodsinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadAllGoodinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadAllGoodinfo")
    @ResponseWrapper(localName = "loadAllGoodinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadAllGoodinfoResponse")
    public ArrayOfGoodsinfo loadAllGoodinfo();

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckUserResponse")
    public String checkUser(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCardAccount", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardAccount")
    @ResponseWrapper(localName = "loadCardAccountResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardAccountResponse")
    public String loadCardAccount(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.Nointernalcardinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadNointernalcardinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadNointernalcardinfo")
    @ResponseWrapper(localName = "loadNointernalcardinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadNointernalcardinfoResponse")
    public Nointernalcardinfo loadNointernalcardinfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.Evaluation
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadEvaluation", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEvaluation")
    @ResponseWrapper(localName = "loadEvaluationResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEvaluationResponse")
    public Evaluation loadEvaluation(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.Companyinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCompanyinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCompanyinfo")
    @ResponseWrapper(localName = "loadCompanyinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCompanyinfoResponse")
    public Companyinfo loadCompanyinfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadNewEmpInfoByComp", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadNewEmpInfoByComp")
    @ResponseWrapper(localName = "loadNewEmpInfoByCompResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadNewEmpInfoByCompResponse")
    public String loadNewEmpInfoByComp(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        int in2);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadOrderById", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderById")
    @ResponseWrapper(localName = "loadOrderByIdResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderByIdResponse")
    public String loadOrderById(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "findGoodBarInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.FindGoodBarInfo")
    @ResponseWrapper(localName = "findGoodBarInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.FindGoodBarInfoResponse")
    public String findGoodBarInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in9
     * @param in10
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveNewOrders", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveNewOrders")
    @ResponseWrapper(localName = "saveNewOrdersResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveNewOrdersResponse")
    public String saveNewOrders(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.amani.com")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://services.amani.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://services.amani.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://services.amani.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://services.amani.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://services.amani.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://services.amani.com")
        String in10);

    /**
     * 
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "checkDyqNo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckDyqNo")
    @ResponseWrapper(localName = "checkDyqNoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckDyqNoResponse")
    public boolean checkDyqNo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.Wxbandcard
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadWxbandcard", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadWxbandcard")
    @ResponseWrapper(localName = "loadWxbandcardResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadWxbandcardResponse")
    public Wxbandcard loadWxbandcard(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadwWeixinclents", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadwWeixinclents")
    @ResponseWrapper(localName = "loadwWeixinclentsResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadwWeixinclentsResponse")
    public String loadwWeixinclents(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "updateCardPassword", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdateCardPassword")
    @ResponseWrapper(localName = "updateCardPasswordResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdateCardPasswordResponse")
    public boolean updateCardPassword(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadOrderByOpenId", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderByOpenId")
    @ResponseWrapper(localName = "loadOrderByOpenIdResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderByOpenIdResponse")
    public String loadOrderByOpenId(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @param in8
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveOrders", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrders")
    @ResponseWrapper(localName = "saveOrdersResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrdersResponse")
    public boolean saveOrders(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.amani.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://services.amani.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://services.amani.com")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://services.amani.com")
        int in7,
        @WebParam(name = "in8", targetNamespace = "http://services.amani.com")
        String in8);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "wxPost", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.WxPost")
    @ResponseWrapper(localName = "wxPostResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.WxPostResponse")
    public boolean wxPost(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfCardinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCardInfos", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardInfos")
    @ResponseWrapper(localName = "loadCardInfosResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardInfosResponse")
    public ArrayOfCardinfo loadCardInfos(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadDqyNo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadDqyNo")
    @ResponseWrapper(localName = "loadDqyNoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadDqyNoResponse")
    public String loadDqyNo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.amani.com")
        String in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveInventory", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveInventory")
    @ResponseWrapper(localName = "saveInventoryResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveInventoryResponse")
    public String saveInventory(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveOrderPrjInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrderPrjInfo")
    @ResponseWrapper(localName = "saveOrderPrjInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrderPrjInfoResponse")
    public boolean saveOrderPrjInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadOrderByEmp", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderByEmp")
    @ResponseWrapper(localName = "loadOrderByEmpResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderByEmpResponse")
    public String loadOrderByEmp(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfRoominfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadRoomInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadRoomInfo")
    @ResponseWrapper(localName = "loadRoomInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadRoomInfoResponse")
    public ArrayOfRoominfo loadRoomInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadEmpInfoByComp", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEmpInfoByComp")
    @ResponseWrapper(localName = "loadEmpInfoByCompResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEmpInfoByCompResponse")
    public String loadEmpInfoByComp(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "checkCardPassword", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckCardPassword")
    @ResponseWrapper(localName = "checkCardPasswordResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckCardPasswordResponse")
    public boolean checkCardPassword(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadStaffinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStaffinfo")
    @ResponseWrapper(localName = "loadStaffinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStaffinfoResponse")
    public String loadStaffinfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveEvaluation", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveEvaluation")
    @ResponseWrapper(localName = "saveEvaluationResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveEvaluationResponse")
    public boolean saveEvaluation(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        double in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.amani.com")
        double in4);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadOrders", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrders")
    @ResponseWrapper(localName = "loadOrdersResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrdersResponse")
    public String loadOrders(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadStartBeautyInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStartBeautyInfo")
    @ResponseWrapper(localName = "loadStartBeautyInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStartBeautyInfoResponse")
    public String loadStartBeautyInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadOrderDetal", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderDetal")
    @ResponseWrapper(localName = "loadOrderDetalResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadOrderDetalResponse")
    public String loadOrderDetal(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "bandStaffInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.BandStaffInfo")
    @ResponseWrapper(localName = "bandStaffInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.BandStaffInfoResponse")
    public boolean bandStaffInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfCompanyinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadAllCompanyinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadAllCompanyinfo")
    @ResponseWrapper(localName = "loadAllCompanyinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadAllCompanyinfoResponse")
    public ArrayOfCompanyinfo loadAllCompanyinfo();

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "saveOrderEmpInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrderEmpInfo")
    @ResponseWrapper(localName = "saveOrderEmpInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.SaveOrderEmpInfoResponse")
    public boolean saveOrderEmpInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.amani.com")
        String in4);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadVouchers", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadVouchers")
    @ResponseWrapper(localName = "loadVouchersResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadVouchersResponse")
    public String loadVouchers();

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadStartHairInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStartHairInfo")
    @ResponseWrapper(localName = "loadStartHairInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadStartHairInfoResponse")
    public String loadStartHairInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCardproaccounts", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardproaccounts")
    @ResponseWrapper(localName = "loadCardproaccountsResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardproaccountsResponse")
    public String loadCardproaccounts(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "deleteInventoryByInventBill", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.DeleteInventoryByInventBill")
    @ResponseWrapper(localName = "deleteInventoryByInventBillResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.DeleteInventoryByInventBillResponse")
    public String deleteInventoryByInventBill(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "deleteInventoryByBill", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.DeleteInventoryByBill")
    @ResponseWrapper(localName = "deleteInventoryByBillResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.DeleteInventoryByBillResponse")
    public String deleteInventoryByBill(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadcCardaccountchangehistories", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadcCardaccountchangehistories")
    @ResponseWrapper(localName = "loadcCardaccountchangehistoriesResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadcCardaccountchangehistoriesResponse")
    public String loadcCardaccountchangehistories(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "updBillState", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdBillState")
    @ResponseWrapper(localName = "updBillStateResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdBillStateResponse")
    public boolean updBillState(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "checkBillState", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckBillState")
    @ResponseWrapper(localName = "checkBillStateResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckBillStateResponse")
    public String checkBillState(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfProjectinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadProjectinfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadProjectinfo")
    @ResponseWrapper(localName = "loadProjectinfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadProjectinfoResponse")
    public ArrayOfProjectinfo loadProjectinfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "updOrderState", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdOrderState")
    @ResponseWrapper(localName = "updOrderStateResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.UpdOrderStateResponse")
    public boolean updOrderState(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "addInventory", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.AddInventory")
    @ResponseWrapper(localName = "addInventoryResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.AddInventoryResponse")
    public String addInventory(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCompByCardNo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCompByCardNo")
    @ResponseWrapper(localName = "loadCompByCardNoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCompByCardNoResponse")
    public String loadCompByCardNo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadEmpInfoByDept", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEmpInfoByDept")
    @ResponseWrapper(localName = "loadEmpInfoByDeptResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadEmpInfoByDeptResponse")
    public String loadEmpInfoByDept(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "lsDnointernalcardinfos", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LsDnointernalcardinfos")
    @ResponseWrapper(localName = "lsDnointernalcardinfosResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LsDnointernalcardinfosResponse")
    public String lsDnointernalcardinfos(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.Cardinfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCardInfo", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardInfo")
    @ResponseWrapper(localName = "loadCardInfoResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCardInfoResponse")
    public Cardinfo loadCardInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadMirror", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadMirror")
    @ResponseWrapper(localName = "loadMirrorResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadMirrorResponse")
    public ArrayOfString loadMirror(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfCategoryinfoId
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadCategory", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCategory")
    @ResponseWrapper(localName = "loadCategoryResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadCategoryResponse")
    public ArrayOfCategoryinfoId loadCategory(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.ArrayOfVouchersdetal
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "loadVouchersdetalsById", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadVouchersdetalsById")
    @ResponseWrapper(localName = "loadVouchersdetalsByIdResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.LoadVouchersdetalsByIdResponse")
    public ArrayOfVouchersdetal loadVouchersdetalsById(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "checkGoodBar", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckGoodBar")
    @ResponseWrapper(localName = "checkGoodBarResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.CheckGoodBarResponse")
    public String checkGoodBar(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

}
