
package amani.wechat.platform.webserviceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonService", targetNamespace = "http://services.amani.com", wsdlLocation = "http://localhost:8080/AMNCommonService/services/CommonService?wsdl")
public class CommonService
    extends Service
{

    private final static URL COMMONSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMMONSERVICE_EXCEPTION;
    private final static QName COMMONSERVICE_QNAME = new QName("http://services.amani.com", "CommonService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AMNCommonService/services/CommonService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONSERVICE_WSDL_LOCATION = url;
        COMMONSERVICE_EXCEPTION = e;
    }

    public CommonService() {
        super(__getWsdlLocation(), COMMONSERVICE_QNAME);
    }

    public CommonService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONSERVICE_QNAME, features);
    }

    public CommonService(URL wsdlLocation) {
        super(wsdlLocation, COMMONSERVICE_QNAME);
    }

    public CommonService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONSERVICE_QNAME, features);
    }

    public CommonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonServicePortType
     */
    @WebEndpoint(name = "CommonServiceHttpPort")
    public CommonServicePortType getCommonServiceHttpPort() {
        return super.getPort(new QName("http://services.amani.com", "CommonServiceHttpPort"), CommonServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonServicePortType
     */
    @WebEndpoint(name = "CommonServiceHttpPort")
    public CommonServicePortType getCommonServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.amani.com", "CommonServiceHttpPort"), CommonServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONSERVICE_EXCEPTION!= null) {
            throw COMMONSERVICE_EXCEPTION;
        }
        return COMMONSERVICE_WSDL_LOCATION;
    }

}
