package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnAccessStatistics generated by hbm2java
 */
public class AmnAccessStatistics implements java.io.Serializable {

	private Integer ipid;
	private Integer mid;
	private String ipdata;
	private int iptime;

	public AmnAccessStatistics() {
	}

	public AmnAccessStatistics(String ipdata, int iptime) {
		this.ipdata = ipdata;
		this.iptime = iptime;
	}

	public AmnAccessStatistics(Integer mid, String ipdata, int iptime) {
		this.mid = mid;
		this.ipdata = ipdata;
		this.iptime = iptime;
	}

	public Integer getIpid() {
		return this.ipid;
	}

	public void setIpid(Integer ipid) {
		this.ipid = ipid;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getIpdata() {
		return this.ipdata;
	}

	public void setIpdata(String ipdata) {
		this.ipdata = ipdata;
	}

	public int getIptime() {
		return this.iptime;
	}

	public void setIptime(int iptime) {
		this.iptime = iptime;
	}

}
