package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AmnOrders generated by hbm2java
 */
public class AmnOrders implements java.io.Serializable {

	private Integer id;
	private long bianhao;
	private String openid;
	private int cardid;
	private BigDecimal freight;
	private BigDecimal producttotal;
	private BigDecimal total;
	private boolean paystatus;
	private int paytime;
	private int createtime;
	private byte delivery;
	private String compid;
	private String compname;
	private String realname;
	private String address;
	private String zipcode;
	private String tel;
	private String email;

	public AmnOrders() {
	}

	public AmnOrders(long bianhao, int cardid, BigDecimal freight,
			BigDecimal producttotal, BigDecimal total, boolean paystatus,
			int paytime, int createtime, byte delivery, String compname) {
		this.bianhao = bianhao;
		this.cardid = cardid;
		this.freight = freight;
		this.producttotal = producttotal;
		this.total = total;
		this.paystatus = paystatus;
		this.paytime = paytime;
		this.createtime = createtime;
		this.delivery = delivery;
		this.compname = compname;
	}

	public AmnOrders(long bianhao, String openid, int cardid,
			BigDecimal freight, BigDecimal producttotal, BigDecimal total,
			boolean paystatus, int paytime, int createtime, byte delivery,
			String compid, String compname, String realname, String address,
			String zipcode, String tel, String email) {
		this.bianhao = bianhao;
		this.openid = openid;
		this.cardid = cardid;
		this.freight = freight;
		this.producttotal = producttotal;
		this.total = total;
		this.paystatus = paystatus;
		this.paytime = paytime;
		this.createtime = createtime;
		this.delivery = delivery;
		this.compid = compid;
		this.compname = compname;
		this.realname = realname;
		this.address = address;
		this.zipcode = zipcode;
		this.tel = tel;
		this.email = email;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public long getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(long bianhao) {
		this.bianhao = bianhao;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public int getCardid() {
		return this.cardid;
	}

	public void setCardid(int cardid) {
		this.cardid = cardid;
	}

	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	public BigDecimal getProducttotal() {
		return this.producttotal;
	}

	public void setProducttotal(BigDecimal producttotal) {
		this.producttotal = producttotal;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public boolean isPaystatus() {
		return this.paystatus;
	}

	public void setPaystatus(boolean paystatus) {
		this.paystatus = paystatus;
	}

	public int getPaytime() {
		return this.paytime;
	}

	public void setPaytime(int paytime) {
		this.paytime = paytime;
	}

	public int getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(int createtime) {
		this.createtime = createtime;
	}

	public byte getDelivery() {
		return this.delivery;
	}

	public void setDelivery(byte delivery) {
		this.delivery = delivery;
	}

	public String getCompid() {
		return this.compid;
	}

	public void setCompid(String compid) {
		this.compid = compid;
	}

	public String getCompname() {
		return this.compname;
	}

	public void setCompname(String compname) {
		this.compname = compname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
