package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AmnOrdersItem generated by hbm2java
 */
public class AmnOrdersItem implements java.io.Serializable {

	private Integer id;
	private Long bianhao;
	private int pid;
	private String name;
	private BigDecimal price;
	private String coupontype;
	private String icon;
	private int num;
	private String couponcode;
	private String openid;
	private String shares;

	public AmnOrdersItem() {
	}

	public AmnOrdersItem(int pid, int num) {
		this.pid = pid;
		this.num = num;
	}

	public AmnOrdersItem(Long bianhao, int pid, String name, BigDecimal price,
			String coupontype, String icon, int num, String couponcode,
			String openid, String shares) {
		this.bianhao = bianhao;
		this.pid = pid;
		this.name = name;
		this.price = price;
		this.coupontype = coupontype;
		this.icon = icon;
		this.num = num;
		this.couponcode = couponcode;
		this.openid = openid;
		this.shares = shares;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getBianhao() {
		return this.bianhao;
	}

	public void setBianhao(Long bianhao) {
		this.bianhao = bianhao;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getCoupontype() {
		return this.coupontype;
	}

	public void setCoupontype(String coupontype) {
		this.coupontype = coupontype;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getCouponcode() {
		return this.couponcode;
	}

	public void setCouponcode(String couponcode) {
		this.couponcode = couponcode;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getShares() {
		return this.shares;
	}

	public void setShares(String shares) {
		this.shares = shares;
	}

}
