package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnProductRelevance generated by hbm2java
 */
public class AmnProductRelevance implements java.io.Serializable {

	private AmnProductRelevanceId id;

	public AmnProductRelevance() {
	}

	public AmnProductRelevance(AmnProductRelevanceId id) {
		this.id = id;
	}

	public AmnProductRelevanceId getId() {
		return this.id;
	}

	public void setId(AmnProductRelevanceId id) {
		this.id = id;
	}

}
