package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnProduct generated by hbm2java
 */
public class AmnProduct implements java.io.Serializable {

	private Integer id;
	private int cid;
	private String name;
	private float price;
	private int num;
	private byte type;
	private String coupontype;
	private String icon;
	private String content;
	private String intro;
	private boolean isopen;
	private boolean ishot;
	private int sort;
	private int createtime;

	public AmnProduct() {
	}

	public AmnProduct(int cid, float price, int num, byte type,
			String coupontype, boolean isopen, boolean ishot, int sort,
			int createtime) {
		this.cid = cid;
		this.price = price;
		this.num = num;
		this.type = type;
		this.coupontype = coupontype;
		this.isopen = isopen;
		this.ishot = ishot;
		this.sort = sort;
		this.createtime = createtime;
	}

	public AmnProduct(int cid, String name, float price, int num, byte type,
			String coupontype, String icon, String content, String intro,
			boolean isopen, boolean ishot, int sort, int createtime) {
		this.cid = cid;
		this.name = name;
		this.price = price;
		this.num = num;
		this.type = type;
		this.coupontype = coupontype;
		this.icon = icon;
		this.content = content;
		this.intro = intro;
		this.isopen = isopen;
		this.ishot = ishot;
		this.sort = sort;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	public String getCoupontype() {
		return this.coupontype;
	}

	public void setCoupontype(String coupontype) {
		this.coupontype = coupontype;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public boolean isIsopen() {
		return this.isopen;
	}

	public void setIsopen(boolean isopen) {
		this.isopen = isopen;
	}

	public boolean isIshot() {
		return this.ishot;
	}

	public void setIshot(boolean ishot) {
		this.ishot = ishot;
	}

	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	public int getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(int createtime) {
		this.createtime = createtime;
	}

}
