package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnReply generated by hbm2java
 */
public class AmnReply implements java.io.Serializable {

	private Integer id;
	private byte cate;
	private byte type;
	private String title;
	private String content;
	private boolean isopen;
	private int createtime;

	public AmnReply() {
	}

	public AmnReply(byte cate, byte type, boolean isopen, int createtime) {
		this.cate = cate;
		this.type = type;
		this.isopen = isopen;
		this.createtime = createtime;
	}

	public AmnReply(byte cate, byte type, String title, String content,
			boolean isopen, int createtime) {
		this.cate = cate;
		this.type = type;
		this.title = title;
		this.content = content;
		this.isopen = isopen;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte getCate() {
		return this.cate;
	}

	public void setCate(byte cate) {
		this.cate = cate;
	}

	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public boolean isIsopen() {
		return this.isopen;
	}

	public void setIsopen(boolean isopen) {
		this.isopen = isopen;
	}

	public int getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(int createtime) {
		this.createtime = createtime;
	}

}
