package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnSysmenu generated by hbm2java
 */
public class AmnSysmenu implements java.io.Serializable {

	private Integer id;
	private String name;
	private String topkey;
	private String mkey;
	private int sub;
	private Boolean isopen;
	private Integer sort;
	private String icon;
	private Boolean issys;
	private Integer ctime;

	public AmnSysmenu() {
	}

	public AmnSysmenu(String name, String mkey, int sub) {
		this.name = name;
		this.mkey = mkey;
		this.sub = sub;
	}

	public AmnSysmenu(String name, String topkey, String mkey, int sub,
			Boolean isopen, Integer sort, String icon, Boolean issys,
			Integer ctime) {
		this.name = name;
		this.topkey = topkey;
		this.mkey = mkey;
		this.sub = sub;
		this.isopen = isopen;
		this.sort = sort;
		this.icon = icon;
		this.issys = issys;
		this.ctime = ctime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTopkey() {
		return this.topkey;
	}

	public void setTopkey(String topkey) {
		this.topkey = topkey;
	}

	public String getMkey() {
		return this.mkey;
	}

	public void setMkey(String mkey) {
		this.mkey = mkey;
	}

	public int getSub() {
		return this.sub;
	}

	public void setSub(int sub) {
		this.sub = sub;
	}

	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}

	public Integer getCtime() {
		return this.ctime;
	}

	public void setCtime(Integer ctime) {
		this.ctime = ctime;
	}

}
