package amani.wechart.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnSms generated by hbm2java
 */
public class AmnSms implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String msgtype;
	private String content;
	private byte state;
	private boolean isreply;
	private int createtime;

	public AmnSms() {
	}

	public AmnSms(String openid, byte state, boolean isreply, int createtime) {
		this.openid = openid;
		this.state = state;
		this.isreply = isreply;
		this.createtime = createtime;
	}

	public AmnSms(String openid, String msgtype, String content, byte state,
			boolean isreply, int createtime) {
		this.openid = openid;
		this.msgtype = msgtype;
		this.content = content;
		this.state = state;
		this.isreply = isreply;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public byte getState() {
		return this.state;
	}

	public void setState(byte state) {
		this.state = state;
	}

	public boolean isIsreply() {
		return this.isreply;
	}

	public void setIsreply(boolean isreply) {
		this.isreply = isreply;
	}

	public int getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(int createtime) {
		this.createtime = createtime;
	}

}
