package com.amani.model;
// default package



/**
 * Gam26Id generated by MyEclipse - Hibernate Tools
 */

public class CompchaininfoId  implements java.io.Serializable {


    // Fields    

     private String curcomp;
     private String relationcomp;


    // Constructors

    /** default constructor */
    public CompchaininfoId() {
    }

    
    /** full constructor */
    public CompchaininfoId(String curcomp, String relationcomp) {
        this.curcomp = curcomp;
        this.relationcomp = relationcomp;
    }


	public String getCurcomp() {
		return curcomp;
	}


	public void setCurcomp(String curcomp) {
		this.curcomp = curcomp;
	}


	public String getRelationcomp() {
		return relationcomp;
	}


	public void setRelationcomp(String relationcomp) {
		this.relationcomp = relationcomp;
	}




}