
package amani.wechat.platform.webserviceClient.imageService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImageCloudServicePortType", targetNamespace = "http://services.amani.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImageCloudServicePortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.imageService.UploadedFileItem
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.UploadFileResponse")
    public UploadedFileItem uploadFile(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        byte[] in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "getFileUrl1", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFileUrl1")
    @ResponseWrapper(localName = "getFileUrl1Response", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFileUrl1Response")
    public String getFileUrl1(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.amani.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://services.amani.com")
        int in3);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "containsFile", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.ContainsFile")
    @ResponseWrapper(localName = "containsFileResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.ContainsFileResponse")
    public Boolean containsFile(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns amani.wechat.platform.webserviceClient.imageService.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "getFiles", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFiles")
    @ResponseWrapper(localName = "getFilesResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFilesResponse")
    public ArrayOfString getFiles(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0);

    /**
     * 
     * @return
     *     returns amani.wechat.platform.webserviceClient.imageService.ArrayOfString
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "getBuckets", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetBuckets")
    @ResponseWrapper(localName = "getBucketsResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetBucketsResponse")
    public ArrayOfString getBuckets();

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.amani.com")
    @RequestWrapper(localName = "getFileUrl", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFileUrl")
    @ResponseWrapper(localName = "getFileUrlResponse", targetNamespace = "http://services.amani.com", className = "amani.wechat.platform.webserviceClient.imageService.GetFileUrlResponse")
    public String getFileUrl(
        @WebParam(name = "in0", targetNamespace = "http://services.amani.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.amani.com")
        String in1);

}
