package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnAccount generated by hbm2java
 */
@Entity
@Table(name = "amn_account", catalog = "amn")
public class AmnAccount implements java.io.Serializable {

	private Integer id;
	private Integer groupid;
	private Integer adminid;
	private Integer memberid;
	private String username;
	private String password;
	private String email;
	private Integer logintime;
	private Boolean state;
	private Integer regtime;

	public AmnAccount() {
	}

	public AmnAccount(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public AmnAccount(Integer groupid, Integer adminid, Integer memberid,
			String username, String password, String email, Integer logintime,
			Boolean state, Integer regtime) {
		this.groupid = groupid;
		this.adminid = adminid;
		this.memberid = memberid;
		this.username = username;
		this.password = password;
		this.email = email;
		this.logintime = logintime;
		this.state = state;
		this.regtime = regtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "groupid")
	public Integer getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	@Column(name = "adminid")
	public Integer getAdminid() {
		return this.adminid;
	}

	public void setAdminid(Integer adminid) {
		this.adminid = adminid;
	}

	@Column(name = "memberid")
	public Integer getMemberid() {
		return this.memberid;
	}

	public void setMemberid(Integer memberid) {
		this.memberid = memberid;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "logintime")
	public Integer getLogintime() {
		return this.logintime;
	}

	public void setLogintime(Integer logintime) {
		this.logintime = logintime;
	}

	@Column(name = "state")
	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	@Column(name = "regtime")
	public Integer getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Integer regtime) {
		this.regtime = regtime;
	}

}
