package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnBarcode generated by hbm2java
 */
@Entity
@Table(name = "amn_barcode", catalog = "amn")
public class AmnBarcode implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String cardid;
	private String uuid;
	private Long validate;
	private BigDecimal price;
	private boolean status;
	private int solvetime;
	private String orderid;
	private String scancode;

	public AmnBarcode() {
	}

	public AmnBarcode(boolean status, int solvetime) {
		this.status = status;
		this.solvetime = solvetime;
	}

	public AmnBarcode(String openid, String cardid, String uuid, Long validate,
			BigDecimal price, boolean status, int solvetime, String orderid,
			String scancode) {
		this.openid = openid;
		this.cardid = cardid;
		this.uuid = uuid;
		this.validate = validate;
		this.price = price;
		this.status = status;
		this.solvetime = solvetime;
		this.orderid = orderid;
		this.scancode = scancode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "openid")
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "cardid", length = 50)
	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	@Column(name = "uuid")
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "validate")
	public Long getValidate() {
		return this.validate;
	}

	public void setValidate(Long validate) {
		this.validate = validate;
	}

	@Column(name = "price", precision = 11)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "solvetime", nullable = false)
	public int getSolvetime() {
		return this.solvetime;
	}

	public void setSolvetime(int solvetime) {
		this.solvetime = solvetime;
	}

	@Column(name = "orderid")
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "scancode")
	public String getScancode() {
		return this.scancode;
	}

	public void setScancode(String scancode) {
		this.scancode = scancode;
	}

}
