package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * AmnCart generated by hbm2java
 */
public class AmnCart implements java.io.Serializable {

	private Integer id;
	private int pid;
	private String name;
	private BigDecimal price;
	private String coupontype;
	private String icon;
	private int num;
	private String openid;

	public AmnCart() {
	}

	public AmnCart(int pid, int num) {
		this.pid = pid;
		this.num = num;
	}

	public AmnCart(int pid, String name, BigDecimal price, String coupontype,
			String icon, int num, String openid) {
		this.pid = pid;
		this.name = name;
		this.price = price;
		this.coupontype = coupontype;
		this.icon = icon;
		this.num = num;
		this.openid = openid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getCoupontype() {
		return this.coupontype;
	}

	public void setCoupontype(String coupontype) {
		this.coupontype = coupontype;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

}
