package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnCard generated by hbm2java
 */
public class AmnCard implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String cardid;
	private String mobile;
	private String realname;

	public AmnCard() {
	}

	public AmnCard(String openid, String cardid, String mobile, String realname) {
		this.openid = openid;
		this.cardid = cardid;
		this.mobile = mobile;
		this.realname = realname;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

}
