package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnConfigs generated by hbm2java
 */
@Entity
@Table(name = "amn_configs", catalog = "amn")
public class AmnConfigs implements java.io.Serializable {

	private Integer id;
	private String token;
	private String appid;
	private String appsecret;
	private String accessToken;
	private int expiresIn;
	private int tokentime;
	private String mchid;
	private String key;
	private String jsTicket;
	private int jsExpires;

	public AmnConfigs() {
	}

	public AmnConfigs(int expiresIn, int tokentime, int jsExpires) {
		this.expiresIn = expiresIn;
		this.tokentime = tokentime;
		this.jsExpires = jsExpires;
	}

	public AmnConfigs(String token, String appid, String appsecret,
			String accessToken, int expiresIn, int tokentime, String mchid,
			String key, String jsTicket, int jsExpires) {
		this.token = token;
		this.appid = appid;
		this.appsecret = appsecret;
		this.accessToken = accessToken;
		this.expiresIn = expiresIn;
		this.tokentime = tokentime;
		this.mchid = mchid;
		this.key = key;
		this.jsTicket = jsTicket;
		this.jsExpires = jsExpires;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "appid")
	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	@Column(name = "appsecret")
	public String getAppsecret() {
		return this.appsecret;
	}

	public void setAppsecret(String appsecret) {
		this.appsecret = appsecret;
	}

	@Column(name = "access_token")
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "expires_in", nullable = false)
	public int getExpiresIn() {
		return this.expiresIn;
	}

	public void setExpiresIn(int expiresIn) {
		this.expiresIn = expiresIn;
	}

	@Column(name = "tokentime", nullable = false)
	public int getTokentime() {
		return this.tokentime;
	}

	public void setTokentime(int tokentime) {
		this.tokentime = tokentime;
	}

	@Column(name = "mchid")
	public String getMchid() {
		return this.mchid;
	}

	public void setMchid(String mchid) {
		this.mchid = mchid;
	}

	@Column(name = "`key`")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "js_ticket")
	public String getJsTicket() {
		return this.jsTicket;
	}

	public void setJsTicket(String jsTicket) {
		this.jsTicket = jsTicket;
	}

	@Column(name = "js_expires", nullable = false)
	public int getJsExpires() {
		return this.jsExpires;
	}

	public void setJsExpires(int jsExpires) {
		this.jsExpires = jsExpires;
	}

}
