package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnGroups generated by hbm2java
 */
@Entity
@Table(name = "amn_groups", catalog = "amn")
public class AmnGroups implements java.io.Serializable {

	private Short groupid;
	private String grouptitle;
	private boolean ifdefault;
	private String adminright;

	public AmnGroups() {
	}

	public AmnGroups(String grouptitle, boolean ifdefault) {
		this.grouptitle = grouptitle;
		this.ifdefault = ifdefault;
	}

	public AmnGroups(String grouptitle, boolean ifdefault, String adminright) {
		this.grouptitle = grouptitle;
		this.ifdefault = ifdefault;
		this.adminright = adminright;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "groupid", unique = true, nullable = false)
	public Short getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Short groupid) {
		this.groupid = groupid;
	}

	@Column(name = "grouptitle", nullable = false, length = 30)
	public String getGrouptitle() {
		return this.grouptitle;
	}

	public void setGrouptitle(String grouptitle) {
		this.grouptitle = grouptitle;
	}

	@Column(name = "ifdefault", nullable = false)
	public boolean isIfdefault() {
		return this.ifdefault;
	}

	public void setIfdefault(boolean ifdefault) {
		this.ifdefault = ifdefault;
	}

	@Column(name = "adminright", length = 65535)
	public String getAdminright() {
		return this.adminright;
	}

	public void setAdminright(String adminright) {
		this.adminright = adminright;
	}

}
