package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnMpages generated by hbm2java
 */
public class AmnMpages implements java.io.Serializable {

	private Integer id;
	private Integer uid;
	private String musicPath;
	private String sharePath;
	private String shareTitle;
	private String shareIntro;
	private String pageContent;
	private String formImg;
	private Boolean specType;
	private Integer formMax;
	private String formMaxMessage;
	private String formBtnText1;
	private String formSuccessUrl;
	private String formTel;
	private String formContent;
	private Byte isopen;
	private Byte status;
	private String seo;
	private Integer createtime;
	private Integer pv;

	public AmnMpages() {
	}

	public AmnMpages(Integer uid, String musicPath, String sharePath,
			String shareTitle, String shareIntro, String pageContent,
			String formImg, Boolean specType, Integer formMax,
			String formMaxMessage, String formBtnText1, String formSuccessUrl,
			String formTel, String formContent, Byte isopen, Byte status,
			String seo, Integer createtime, Integer pv) {
		this.uid = uid;
		this.musicPath = musicPath;
		this.sharePath = sharePath;
		this.shareTitle = shareTitle;
		this.shareIntro = shareIntro;
		this.pageContent = pageContent;
		this.formImg = formImg;
		this.specType = specType;
		this.formMax = formMax;
		this.formMaxMessage = formMaxMessage;
		this.formBtnText1 = formBtnText1;
		this.formSuccessUrl = formSuccessUrl;
		this.formTel = formTel;
		this.formContent = formContent;
		this.isopen = isopen;
		this.status = status;
		this.seo = seo;
		this.createtime = createtime;
		this.pv = pv;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getMusicPath() {
		return this.musicPath;
	}

	public void setMusicPath(String musicPath) {
		this.musicPath = musicPath;
	}

	public String getSharePath() {
		return this.sharePath;
	}

	public void setSharePath(String sharePath) {
		this.sharePath = sharePath;
	}

	public String getShareTitle() {
		return this.shareTitle;
	}

	public void setShareTitle(String shareTitle) {
		this.shareTitle = shareTitle;
	}

	public String getShareIntro() {
		return this.shareIntro;
	}

	public void setShareIntro(String shareIntro) {
		this.shareIntro = shareIntro;
	}

	public String getPageContent() {
		return this.pageContent;
	}

	public void setPageContent(String pageContent) {
		this.pageContent = pageContent;
	}

	public String getFormImg() {
		return this.formImg;
	}

	public void setFormImg(String formImg) {
		this.formImg = formImg;
	}

	public Boolean getSpecType() {
		return this.specType;
	}

	public void setSpecType(Boolean specType) {
		this.specType = specType;
	}

	public Integer getFormMax() {
		return this.formMax;
	}

	public void setFormMax(Integer formMax) {
		this.formMax = formMax;
	}

	public String getFormMaxMessage() {
		return this.formMaxMessage;
	}

	public void setFormMaxMessage(String formMaxMessage) {
		this.formMaxMessage = formMaxMessage;
	}

	public String getFormBtnText1() {
		return this.formBtnText1;
	}

	public void setFormBtnText1(String formBtnText1) {
		this.formBtnText1 = formBtnText1;
	}

	public String getFormSuccessUrl() {
		return this.formSuccessUrl;
	}

	public void setFormSuccessUrl(String formSuccessUrl) {
		this.formSuccessUrl = formSuccessUrl;
	}

	public String getFormTel() {
		return this.formTel;
	}

	public void setFormTel(String formTel) {
		this.formTel = formTel;
	}

	public String getFormContent() {
		return this.formContent;
	}

	public void setFormContent(String formContent) {
		this.formContent = formContent;
	}

	public Byte getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Byte isopen) {
		this.isopen = isopen;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getSeo() {
		return this.seo;
	}

	public void setSeo(String seo) {
		this.seo = seo;
	}

	public Integer getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Integer createtime) {
		this.createtime = createtime;
	}

	public Integer getPv() {
		return this.pv;
	}

	public void setPv(Integer pv) {
		this.pv = pv;
	}

}
