package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnMessage generated by hbm2java
 */
@Entity
@Table(name = "amn_message", catalog = "amn")
public class AmnMessage implements java.io.Serializable {

	private Integer id;
	private Integer mid;
	private Integer uid;
	private String name;
	private Boolean sex;
	private String contact;
	private String other;
	private Integer subTime;

	public AmnMessage() {
	}

	public AmnMessage(Integer mid, Integer uid, String name, Boolean sex,
			String contact, String other, Integer subTime) {
		this.mid = mid;
		this.uid = uid;
		this.name = name;
		this.sex = sex;
		this.contact = contact;
		this.other = other;
		this.subTime = subTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mid")
	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@Column(name = "contact", length = 128)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "other", length = 65535)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "subTime")
	public Integer getSubTime() {
		return this.subTime;
	}

	public void setSubTime(Integer subTime) {
		this.subTime = subTime;
	}

}
