package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnNewsPic generated by hbm2java
 */
@Entity
@Table(name = "amn_news_pic", catalog = "amn")
public class AmnNewsPic implements java.io.Serializable {

	private Integer id;
	private Integer nid;
	private String path;
	private String content;
	private Integer praise;
	private String favcount;
	private Boolean isrec;
	private Integer sort;
	private Boolean isopen;
	private Integer createtime;

	public AmnNewsPic() {
	}

	public AmnNewsPic(Integer nid, String path, String content, Integer praise,
			String favcount, Boolean isrec, Integer sort, Boolean isopen,
			Integer createtime) {
		this.nid = nid;
		this.path = path;
		this.content = content;
		this.praise = praise;
		this.favcount = favcount;
		this.isrec = isrec;
		this.sort = sort;
		this.isopen = isopen;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nid")
	public Integer getNid() {
		return this.nid;
	}

	public void setNid(Integer nid) {
		this.nid = nid;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "content", length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "praise")
	public Integer getPraise() {
		return this.praise;
	}

	public void setPraise(Integer praise) {
		this.praise = praise;
	}

	@Column(name = "favcount")
	public String getFavcount() {
		return this.favcount;
	}

	public void setFavcount(String favcount) {
		this.favcount = favcount;
	}

	@Column(name = "isrec")
	public Boolean getIsrec() {
		return this.isrec;
	}

	public void setIsrec(Boolean isrec) {
		this.isrec = isrec;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "isopen")
	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

	@Column(name = "createtime")
	public Integer getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Integer createtime) {
		this.createtime = createtime;
	}

}
