package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnNewsComment generated by hbm2java
 */
public class AmnNewsComment implements java.io.Serializable {

	private Integer id;
	private Integer uid;
	private String uname;
	private Integer nid;
	private Integer pid;
	private String content;
	private Integer praise;
	private Boolean isopen;
	private Integer createtime;

	public AmnNewsComment() {
	}

	public AmnNewsComment(Integer uid, String uname, Integer nid, Integer pid,
			String content, Integer praise, Boolean isopen, Integer createtime) {
		this.uid = uid;
		this.uname = uname;
		this.nid = nid;
		this.pid = pid;
		this.content = content;
		this.praise = praise;
		this.isopen = isopen;
		this.createtime = createtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Integer getNid() {
		return this.nid;
	}

	public void setNid(Integer nid) {
		this.nid = nid;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getPraise() {
		return this.praise;
	}

	public void setPraise(Integer praise) {
		this.praise = praise;
	}

	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

	public Integer getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Integer createtime) {
		this.createtime = createtime;
	}

}
