package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnNewsCate generated by hbm2java
 */
public class AmnNewsCate implements java.io.Serializable {

	private Integer id;
	private Integer sub;
	private String name;
	private String icon;
	private String descr;
	private Integer sort;
	private Byte isrec;
	private Boolean issys;
	private Boolean isopen;

	public AmnNewsCate() {
	}

	public AmnNewsCate(Integer sub, String name, String icon, String descr,
			Integer sort, Byte isrec, Boolean issys, Boolean isopen) {
		this.sub = sub;
		this.name = name;
		this.icon = icon;
		this.descr = descr;
		this.sort = sort;
		this.isrec = isrec;
		this.issys = issys;
		this.isopen = isopen;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSub() {
		return this.sub;
	}

	public void setSub(Integer sub) {
		this.sub = sub;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public Byte getIsrec() {
		return this.isrec;
	}

	public void setIsrec(Byte isrec) {
		this.isrec = isrec;
	}

	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}

	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

}
