package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnNewsCate generated by hbm2java
 */
@Entity
@Table(name = "amn_news_cate", catalog = "amn")
public class AmnNewsCate implements java.io.Serializable {

	private Integer id;
	private Integer sub;
	private String name;
	private String icon;
	private String descr;
	private Integer sort;
	private Byte isrec;
	private Boolean issys;
	private Boolean isopen;

	public AmnNewsCate() {
	}

	public AmnNewsCate(Integer sub, String name, String icon, String descr,
			Integer sort, Byte isrec, Boolean issys, Boolean isopen) {
		this.sub = sub;
		this.name = name;
		this.icon = icon;
		this.descr = descr;
		this.sort = sort;
		this.isrec = isrec;
		this.issys = issys;
		this.isopen = isopen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sub")
	public Integer getSub() {
		return this.sub;
	}

	public void setSub(Integer sub) {
		this.sub = sub;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "icon")
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "descr", length = 65535)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "isrec")
	public Byte getIsrec() {
		return this.isrec;
	}

	public void setIsrec(Byte isrec) {
		this.isrec = isrec;
	}

	@Column(name = "issys")
	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}

	@Column(name = "isopen")
	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

}
