package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmnProductRelevance generated by hbm2java
 */
@Entity
@Table(name = "amn_product_relevance", catalog = "amn")
public class AmnProductRelevance implements java.io.Serializable {

	private AmnProductRelevanceId id;

	public AmnProductRelevance() {
	}

	public AmnProductRelevance(AmnProductRelevanceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pid", column = @Column(name = "pid", nullable = false)),
			@AttributeOverride(name = "aid", column = @Column(name = "aid", nullable = false)) })
	public AmnProductRelevanceId getId() {
		return this.id;
	}

	public void setId(AmnProductRelevanceId id) {
		this.id = id;
	}

}
