package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnProductAlbum generated by hbm2java
 */
@Entity
@Table(name = "amn_product_album", catalog = "amn")
public class AmnProductAlbum implements java.io.Serializable {

	private Integer id;
	private int pid;
	private String path;
	private boolean isdef;

	public AmnProductAlbum() {
	}

	public AmnProductAlbum(int pid, boolean isdef) {
		this.pid = pid;
		this.isdef = isdef;
	}

	public AmnProductAlbum(int pid, String path, boolean isdef) {
		this.pid = pid;
		this.path = path;
		this.isdef = isdef;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "path")
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "isdef", nullable = false)
	public boolean isIsdef() {
		return this.isdef;
	}

	public void setIsdef(boolean isdef) {
		this.isdef = isdef;
	}

}
