package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnProductAlbum generated by hbm2java
 */
public class AmnProductAlbum implements java.io.Serializable {

	private Integer id;
	private int pid;
	private String path;
	private boolean isdef;

	public AmnProductAlbum() {
	}

	public AmnProductAlbum(int pid, boolean isdef) {
		this.pid = pid;
		this.isdef = isdef;
	}

	public AmnProductAlbum(int pid, String path, boolean isdef) {
		this.pid = pid;
		this.path = path;
		this.isdef = isdef;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public boolean isIsdef() {
		return this.isdef;
	}

	public void setIsdef(boolean isdef) {
		this.isdef = isdef;
	}

}
