package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnProductcate generated by hbm2java
 */
@Entity
@Table(name = "amn_productcate", catalog = "amn")
public class AmnProductcate implements java.io.Serializable {

	private Integer id;
	private String name;
	private int sub;
	private int sort;
	private boolean isopen;

	public AmnProductcate() {
	}

	public AmnProductcate(int sub, int sort, boolean isopen) {
		this.sub = sub;
		this.sort = sort;
		this.isopen = isopen;
	}

	public AmnProductcate(String name, int sub, int sort, boolean isopen) {
		this.name = name;
		this.sub = sub;
		this.sort = sort;
		this.isopen = isopen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sub", nullable = false)
	public int getSub() {
		return this.sub;
	}

	public void setSub(int sub) {
		this.sub = sub;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@Column(name = "isopen", nullable = false)
	public boolean isIsopen() {
		return this.isopen;
	}

	public void setIsopen(boolean isopen) {
		this.isopen = isopen;
	}

}
