package amani.wechat.platform.dao.entities;

// Generated 2015-6-23 2:29:39 by Hibernate Tools 4.3.1

/**
 * AmnProductKeys generated by hbm2java
 */
public class AmnProductKeys implements java.io.Serializable {

	private Integer id;
	private float freight;
	private String keys;

	public AmnProductKeys() {
	}

	public AmnProductKeys(float freight) {
		this.freight = freight;
	}

	public AmnProductKeys(float freight, String keys) {
		this.freight = freight;
		this.keys = keys;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public float getFreight() {
		return this.freight;
	}

	public void setFreight(float freight) {
		this.freight = freight;
	}

	public String getKeys() {
		return this.keys;
	}

	public void setKeys(String keys) {
		this.keys = keys;
	}

}
