package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnSysmenu generated by hbm2java
 */
@Entity
@Table(name = "amn_sysmenu", catalog = "amn")
public class AmnSysmenu implements java.io.Serializable {

	private Integer id;
	private String name;
	private String topkey;
	private String mkey;
	private int sub;
	private Boolean isopen;
	private Integer sort;
	private String icon;
	private Boolean issys;
	private Integer ctime;

	public AmnSysmenu() {
	}

	public AmnSysmenu(String name, String mkey, int sub) {
		this.name = name;
		this.mkey = mkey;
		this.sub = sub;
	}

	public AmnSysmenu(String name, String topkey, String mkey, int sub,
			Boolean isopen, Integer sort, String icon, Boolean issys,
			Integer ctime) {
		this.name = name;
		this.topkey = topkey;
		this.mkey = mkey;
		this.sub = sub;
		this.isopen = isopen;
		this.sort = sort;
		this.icon = icon;
		this.issys = issys;
		this.ctime = ctime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "topkey", length = 200)
	public String getTopkey() {
		return this.topkey;
	}

	public void setTopkey(String topkey) {
		this.topkey = topkey;
	}

	@Column(name = "mkey", nullable = false, length = 100)
	public String getMkey() {
		return this.mkey;
	}

	public void setMkey(String mkey) {
		this.mkey = mkey;
	}

	@Column(name = "sub", nullable = false)
	public int getSub() {
		return this.sub;
	}

	public void setSub(int sub) {
		this.sub = sub;
	}

	@Column(name = "isopen")
	public Boolean getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Boolean isopen) {
		this.isopen = isopen;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "icon")
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "issys")
	public Boolean getIssys() {
		return this.issys;
	}

	public void setIssys(Boolean issys) {
		this.issys = issys;
	}

	@Column(name = "ctime")
	public Integer getCtime() {
		return this.ctime;
	}

	public void setCtime(Integer ctime) {
		this.ctime = ctime;
	}

}
