package amani.wechat.platform.dao.entities;

// Generated 2015-6-28 1:25:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AmnSms generated by hbm2java
 */
@Entity
@Table(name = "amn_sms", catalog = "amn")
public class AmnSms implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String msgtype;
	private String content;
	private byte state;
	private boolean isreply;
	private int createtime;

	public AmnSms() {
	}

	public AmnSms(String openid, byte state, boolean isreply, int createtime) {
		this.openid = openid;
		this.state = state;
		this.isreply = isreply;
		this.createtime = createtime;
	}

	public AmnSms(String openid, String msgtype, String content, byte state,
			boolean isreply, int createtime) {
		this.openid = openid;
		this.msgtype = msgtype;
		this.content = content;
		this.state = state;
		this.isreply = isreply;
		this.createtime = createtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "openid", nullable = false, length = 50)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "msgtype", length = 50)
	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "state", nullable = false)
	public byte getState() {
		return this.state;
	}

	public void setState(byte state) {
		this.state = state;
	}

	@Column(name = "isreply", nullable = false)
	public boolean isIsreply() {
		return this.isreply;
	}

	public void setIsreply(boolean isreply) {
		this.isreply = isreply;
	}

	@Column(name = "createtime", nullable = false)
	public int getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(int createtime) {
		this.createtime = createtime;
	}

}
